--create database Academy
--use Academy
--create table Student
--( grade nvarchar(10),
--fullname nvarchar(30),
--birthdate date,
--groupNo nvarchar (8)
--)
--Insert into Student (fullname, grade, birthdate, groupNo)
--values
--( 'Elkhan', 'A', '01-01-1500','P114'),
--( 'Elkhan2', 'B', '01-01-1499','P114')
-- delete from Student
 --where fullname='Elkhan2' 
 --delete from Student
 --where fullname='Elkhan2'
-- update Student
--set fullname='Elkhan111',
-- grade='C',
-- birthdate='02-02-2022',
-- groupNo='P839398'
--where fullname='Elkhan'
--select * from Student
--where fullname='Elkkhan'